### ISSUE TITLE
咱就是说，有后端的开源吗

### ISSUE THREAD

**Issue by Snuffel233** [Puggo1145/CQNU-Mini-Program-frontend#1]
如题，没有后端的话不太好参与贡献哦

**Comment by Puggo1145** [comment]
您好，很抱歉这么晚才看到这份 issue。小程序现在正在计划进行整个后端的重构，预计需要到年中之后。为保证平台上同学们的个人隐私与信息安全，如果想参与贡献的话，建议直接联系本人并确认是在校的同学即可

**Comment by Snuffel233** [comment]
你好，可以提供联系方式吗

**Comment by Snuffel233** [comment]
你好，可以提供联系方式吗

**Comment by Puggo1145** [comment]
麻烦先联系我的邮箱 puggoo1145@gamil.com 或者 qq 1375075411，然后交换具体联系方式。不方便在这里留私人联系方式，希望理解
